version: '3.8'

services:
  # Коробка №1: База даних
  db:
    image: postgres:15
    container_name: notes_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: notes_docker_db
    ports:
      - "5433:5432" # Використовуємо порт 5433, щоб не заважати вашій базі на Windows
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Коробка №2: Ваш FastAPI код
  web:
    build: .
    container_name: notes_web_app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:secure_password_123@db:5432/notes_docker_db
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data: